### ISSUE TITLE
Add User-Agent to request

### ISSUE THREAD

**Issue by sanderheilbron** [Woorank/robots-txt#2]
Some servers return a 401 or 403 error when fetching a robots.txt file because the remote server is expecting/requiring a User-Agent.

Some example URLs:
- https://developer.apple.com/
- http://www.letsmoveschools.org/

**robots-txt** only responds when the status code matches a 2xx or 3xx response. Could you add a User-Agent to the request to avoid a 4xx response?

**Comment by Janpot** [comment]
This seems to be undocumented but it should be possible to add a `request` property to the bot configuration with extra options for the http request that is made to get the robots.txt file:

``` js
var bot = robots({
  request: {
    headers: {
      'user-agent': 'my custom user agent'
    }
  }
});
```

**Comment by sanderheilbron** [comment]
Thanks!

**Comment by cwhitten** [comment]
Hi. Is this no longer the case? Trying this with the same issue but it doesn't appear that the header gets applied.

```coffeescript
RobotsTxt = require 'robots-txt'

robotsTxt = RobotsTxt(request:{headers: {'User-Agent': 'custom-agent'}})
```

**Comment by Janpot** [comment]
@cwhitten I just added an [extra test](https://github.com/Woorank/robots-txt/blob/master/test/robots.spec.js#L122) for this and it seems to work. Do you have a test case that fails?

**Comment by cwhitten** [comment]
It was a false positive. `http://www.reviewsanswers.com/` returns a 4xx even if you supply a user-agent. Using sanderheilbron's examples worked fine.
